- name: Provide node01.pubtransit.org Web server
  hosts: all
  remote_user: ubuntu
  vars:
    work_dir: /home/ubuntu/pubtransit
    install_dir: /var/www/html
    hostname: node01.pubtransit.org

  tasks:

  - name: "set host name: {{ hostname }}"
    become: true
    become_user: root
    hostname: name="{{ hostname }}"

  - name: "fix proxy environment"
    become: true
    become_user: root
    script: deploy/get_proxy_env.py /etc/profile.d/proxy.sh

  - name: "update and upgrade apt packages"
    become: true
    become_user: root
    shell: DEBIAN_FRONTEND=noninteractive apt-get update -y && apt-get upgrade -y

  - name: "install apt packages"
    become: true
    become_user: root
    retries: 3
    apt:
      pkg: "{{ item }}"
      state: latest
    with_items:
      - apache2
      - build-essential
      - git
      - python-dev

  - name: "verify pip is present"
    command: "pip --version"
    ignore_errors: true
    register: pip_is_present
    changed_when: false

  - when: pip_is_present.rc != 0
    block:
      - name: "download get-pip.py"
        retries: 3
        get_url:
          url: https://bootstrap.pypa.io/get-pip.py
          dest: ./

      - name: "install pip"
        become: true
        become_user: root
        command: "python ./get-pip.py"

      - name: "delete get-pip.py"
        file:
          state: absent
          path: ./get-pip.py

  - name: "upgrade pip and setuptools"
    when: pip_is_present.rc == 0
    become: true
    become_user: root
    pip:
      name: "{{ item }}"
      state: latest
    with_items:
      - pip
      - setuptools

  - name: "deploy source files to {{ work_dir }}"
    synchronize:
      src: .
      dest: /home/ubuntu
      delete: yes

  - name: "intall or upgrade transit python package and its dependencies"
    become: true
    become_user: root
    retries: 3
    pip:
      name: "{{ work_dir }}"
      state: latest

  - name: "build feeds and html files"
    make:
      chdir: "{{ work_dir }}"
      target: all

  - name: installd feeds and html files
    become: true
    become_user: root
    make:
      chdir: "{{ work_dir }}"
      target: install
