- name: provide www.pubtransit.org server
  hosts: all
  remote_user: ubuntu
  vars:
    transit_dir: ~/transit
  tasks:

  - name: set host name
    become: true
    become_user: root
    hostname: name=node01.pubtransit.org

  - name: fix proxy environment
    become: true
    become_user: root
    script: provision/get_proxy_env.py /etc/profile.d/proxy.sh

  - name: update and upgrade apt packages
    become: true
    become_user: root
    shell: DEBIAN_FRONTEND=noninteractive apt-get update -y && apt-get upgrade -y

  - name: install some basic apt stuff and upgrade installed packages
    become: true
    become_user: root
    retries: 3
    apt:
      pkg: "{{ item }}"
      state: latest
    with_items:
      - git
      - build-essential
      - python-setuptools
      - python-dev
      - apache2

  - name: check to see if pip is already installed
    command: "pip --version"
    ignore_errors: true
    register: pip_is_installed
    changed_when: false

  - block:
      - name: download get-pip.py
        retries: 3
        get_url:
          url: https://bootstrap.pypa.io/get-pip.py
          dest: ./

      - name: install pip
        become: true
        become_user: root
        command: "python ./get-pip.py"

      - name: ensure pip and setuptools are installed at the latest version
        become: true
        become_user: root
        action: pip name="{{ item }}" state=latest
        with_items:
          - setuptools
          - pip

      - name: delete get-pip.py
        file:
          state: absent
          path: ./get-pip.py

    when: pip_is_installed.rc != 0

  - name: deploy transit source files
    synchronize:
      src: .
      dest: /home/ubuntu
      delete: yes

  - name: intall transit python package
    become: true
    become_user: root
    retries: 3
    pip:
      name: /home/ubuntu/transit

  - name: build feeds and html files
    make:
      chdir: /home/ubuntu/transit
      target: all

  - name: installd feeds and html files
    become: true
    become_user: root
    make:
      chdir: /home/ubuntu/transit
      target: install
